export const data = [{
    "id": 1,
    "first_name": "Berne",
    "last_name": "Hubble",
    "email": "bhubble0@google.pl",
    "phone": "455-556-1887"
  }, {
    "id": 2,
    "first_name": "Morgan",
    "last_name": "Linnemann",
    "email": "mlinnemann1@vimeo.com",
    "phone": "551-399-0410"
  }, {
    "id": 3,
    "first_name": "Melita",
    "last_name": "Duesberry",
    "email": "mduesberry2@ibm.com",
    "phone": "877-276-7145"
  }, {
    "id": 4,
    "first_name": "Hercule",
    "last_name": "Witnall",
    "email": "hwitnall3@wp.com",
    "phone": "624-761-4964"
  }, {
    "id": 5,
    "first_name": "Nerte",
    "last_name": "Durrell",
    "email": "ndurrell4@phpbb.com",
    "phone": "237-226-0270"
  }, {
    "id": 6,
    "first_name": "Addia",
    "last_name": "Fay",
    "email": "afay5@tiny.cc",
    "phone": "497-346-1236"
  }, {
    "id": 7,
    "first_name": "Gillan",
    "last_name": "Matejka",
    "email": "gmatejka6@icq.com",
    "phone": "343-732-0549"
  }, {
    "id": 8,
    "first_name": "Piotr",
    "last_name": "Clancy",
    "email": "pclancy7@jimdo.com",
    "phone": "193-177-1333"
  }, {
    "id": 9,
    "first_name": "Lilli",
    "last_name": "Shine",
    "email": "lshine8@wired.com",
    "phone": "561-861-5681"
  }, {
    "id": 10,
    "first_name": "Cheri",
    "last_name": "McKomb",
    "email": "cmckomb9@issuu.com",
    "phone": "427-724-5559"
  }]